### ISSUE TITLE
Data mismatch

### ISSUE THREAD

**Issue by xifen523** [MrBlankness/LightM-UNet#11]
I downloaded the data as per the readme, but after unzipping it, it doesn't match the 801 dataset settings, the unzip ends in nii, not nii.gz, I tried to run `nnUNetv2_plan_and_preprocess -d 801 --verify_dataset_integrity`, but it failed

```
ingerprint extraction...
Dataset801_LiverCT
Traceback (most recent call last):
  File "/home/lk/miniconda3/envs/lightmunet/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/home/lk/workspase/python/segmentation/LightM-UNet/lightm-unet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/lk/workspase/python/segmentation/LightM-UNet/lightm-unet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/lk/workspase/python/segmentation/LightM-UNet/lightm-unet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/home/lk/workspase/python/segmentation/LightM-UNet/lightm-unet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 155, in verify_dataset_integrity
    assert len(dataset) == expected_num_training, 'Did not find the expected number of training cases ' \
AssertionError: Did not find the expected number of training cases (87). Found 0 instead.
Examples: []
```

how to solve this issue  
thank you

**Comment by Xiadonn** [comment]
Have you ever used nnUNet?
Maybe you should change the data format from nii to nii.gz first by yourself.
Note that "file_ending": ".nii.gz" in dataset.json.
