### ISSUE TITLE
请帮忙看一下为啥batch_size=2这样, 硬件条件满足，还报这样的错： Exception ignored in tp_clear of: <class 'memoryview'> Traceback (most recent call last):   File "D:\softwareSetup\anaconda\envs\lightmunet\lib\multiprocessing\connection.py", line 849, in wait     fileno = getattr(o, 'fileno') BufferError: memoryview has 1 exported buffer

### ISSUE THREAD

**Issue by fayeGou** [MrBlankness/LightM-UNet#27]
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 1, 'patch_size': [128, 128, 128], 'median_image_size_in_voxels': [163.0, 197.0, 197.0], 'spacing': [1.0, 1.0, 1.0], 'normalization_schemes': ['CTNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2], 'num_pool_per_axis': [5, 5, 5], 'pool_op_kernel_sizes': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'unet_max_num_features': 320, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': False} 

These are the global plan.json settings:
 {'dataset_name': 'Dataset803_LiverCT', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [1.0, 1.0, 1.0], 'original_median_shape_after_transp': [163, 197, 197], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 3355.22412109375, 'mean': 98.54908752441406, 'median': 99.94701385498047, 'min': -930.7382202148438, 'percentile_00_5': -11.106827735900879, 'percentile_99_5': 187.6694793701172, 'std': 34.5052604675293}}} 

2024-06-19 15:51:57.711867: unpacking dataset...
Exception ignored in tp_clear of: <class 'memoryview'>
Traceback (most recent call last):
  File "D:\softwareSetup\anaconda\envs\lightmunet\lib\multiprocessing\connection.py", line 849, in wait
    fileno = getattr(o, 'fileno')
BufferError: memoryview has 1 exported buffer

**Comment by CsxQAQ** [comment]
解决了吗，我也是这个问题
